apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: tileserv
parameters:
  - name: PG_TILESERV_IMAGE_TAG
    value: "latest"
  - name: IMAGE_REGISTRY
    value: image-registry.apps.silver.devops.gov.bc.ca
  - name: IMAGE_NAMESPACE
    value: e1e498-tools
  - name: PASSWORD_KEY_NAME
    required: true
    value: wps-global
  - name: PASSWORD_KEY
    required: true
    value: tileserv-db-password
  - name: POSTGRES_USER
    required: true
    value: tileserv
  - name: POSTGRES_WRITE_HOST
    required: true
    value: patroni-wps-tileserv-replica
  - name: POSTGRES_DATABASE
    required: true
    value: tileserv
  - name: HOST
    value: wps-dev-tileserv.apps.silver.devops.gov.bc.ca

objects:
  # pgtileserv: 7800
  # varnish: 8080
  # outside: 80
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: tileserv
      name: tileserv
    spec:
      replicas: 2
      selector:
        app: tileserv
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: tileserv
            name: tileserv
        spec:
          containers:
            - name: nginx
              image: ${IMAGE_REGISTRY}/${IMAGE_NAMESPACE}/nginx-tilecache
              imagePullPolicy: Always
              readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                httpGet:
                  path: /health
                  port: 8080
                timeoutSeconds: 1
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                httpGet:
                  path: /health
                  port: 8080
                timeoutSeconds: 1
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 200m
                  memory: 256Mi
            - name: pgtileserv
              image: ${IMAGE_REGISTRY}/${IMAGE_NAMESPACE}/pg_tileserv:${PG_TILESERV_IMAGE_TAG}
              ports:
                - containerPort: 7800
                  protocol: TCP
              env:
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${PASSWORD_KEY_NAME}
                      key: ${PASSWORD_KEY}
                - name: DATABASE_URL
                  value: postgresql://${POSTGRES_USER}:$(POSTGRES_PASSWORD)@${POSTGRES_WRITE_HOST}/${POSTGRES_DATABASE}
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 5
                periodSeconds: 30
                successThreshold: 1
                tcpSocket:
                  port: 7800
                timeoutSeconds: 5
              readinessProbe:
                httpGet:
                  path: /
                  port: 7800
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 30
                successThreshold: 1
                timeoutSeconds: 5
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 200m
                  memory: 512Mi
  - apiVersion: v1
    kind: Service
    metadata:
      name: tileserv
      labels:
        app: tileserv
        name: tileserv
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 80
          targetPort: 8080
      selector:
        name: tileserv
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: tileserv
      labels:
        app: tileserv
        name: tileserv
    spec:
      host: ${HOST}
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: tileserv
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
